// class VerseColl {
		/*let VerseColl.Ids = array["1"2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
		21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,
		41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,
		61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,
		81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,
		101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,
		121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,
		141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,
		161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,
		181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,
		201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,
		221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,
		241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,
		261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,
		281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,
		301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,
		321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,
		341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,
		361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,
		381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,
		401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,
		421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,
		441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,
		461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,
		481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,
		501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,
		521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,
		541,542,543,544];*/
	var Refs = [
	 	"1Th1:1",
		"1Th1:2",
		"1Th1:3",
		"1Th1:4",
		"1Th1:5",
		"1Th1:6",
		"1Th1:7",
		"1Th1:8",
		"1Th1:9",
		"1Th1:10",
		"1Th2:1",
		"1Th2:2",
		"1Th2:3",
		"1Th2:4",
		"1Th2:5",
		"1Th2:6",
		"1Th2:7",
		"1Th2:8",
		"1Th2:9",
		"1Th2:10",
		"1Th2:11",
		"1Th2:12",
		"1Th2:13",
		"1Th2:14",
		"1Th2:15",
		"1Th2:16",
		"1Th2:17",
		"1Th2:18",
		"1Th2:19",
		"1Th2:20",
		"1Th3:1",
		"1Th3:2",
		"1Th3:3",
		"1Th3:4",
		"1Th3:5",
		"1Th3:6",
		"1Th3:7",
		"1Th3:8",
		"1Th3:9",
		"1Th3:10",
		"1Th3:11",
		"1Th3:12",
		"1Th3:13",
		"1Th4:1",
		"1Th4:2",
		"1Th4:3",
		"1Th4:4",
		"1Th4:5",
		"1Th4:6",
		"1Th4:7",
		"1Th4:8",
		"1Th4:9",
		"1Th4:10",
		"1Th4:11",
		"1Th4:12",
		"1Th4:13",
		"1Th4:14",
		"1Th4:15",
		"1Th4:16",
		"1Th4:17",
		"1Th4:18",
		"1Th5:1",
		"1Th5:2",
		"1Th5:3",
		"1Th5:4",
		"1Th5:5",
		"1Th5:6",
		"1Th5:7",
		"1Th5:8",
		"1Th5:9",
		"1Th5:10",
		"1Th5:11",
		"1Th5:12",
		"1Th5:13",
		"1Th5:14",
		"1Th5:15",
		"1Th5:16",
		"1Th5:17",
		"1Th5:18",
		"1Th5:19",
		"1Th5:20",
		"1Th5:21",
		"1Th5:22",
		"1Th5:23",
		"1Th5:24",
		"1Th5:25",
		"1Th5:26",
		"1Th5:27",
		"1Th5:28",
		"2Th1:1",
		"2Th1:2",
		"2Th1:3",
		"2Th1:4",
		"2Th1:5",
		"2Th1:6",
		"2Th1:7",
		"2Th1:8",
		"2Th1:9",
		"2Th1:10",
		"2Th1:11",
		"2Th1:12",
		"2Th2:1",
		"2Th2:2",
		"2Th2:3",
		"2Th2:4",
		"2Th2:5",
		"2Th2:6",
		"2Th2:7",
		"2Th2:8",
		"2Th2:9",
		"2Th2:10",
		"2Th2:11",
		"2Th2:12",
		"2Th2:13",
		"2Th2:14",
		"2Th2:15",
		"2Th2:16",
		"2Th2:17",
		"2Th3:1",
		"2Th3:2",
		"2Th3:3",
		"2Th3:4",
		"2Th3:5",
		"2Th3:6",
		"2Th3:7",
		"2Th3:8",
		"2Th3:9",
		"2Th3:10",
		"2Th3:11",
		"2Th3:12",
		"2Th3:13",
		"2Th3:14",
		"2Th3:15",
		"2Th3:16",
		"2Th3:17",
		"2Th3:18",
		"1Ti1:1",
		"1Ti1:2",
		"1Ti1:3",
		"1Ti1:4",
		"1Ti1:5",
		"1Ti1:6",
		"1Ti1:7",
		"1Ti1:8",
		"1Ti1:9",
		"1Ti1:10",
		"1Ti1:11",
		"1Ti1:12",
		"1Ti1:13",
		"1Ti1:14",
		"1Ti1:15",
		"1Ti1:16",
		"1Ti1:17",
		"1Ti1:18",
		"1Ti1:19",
		"1Ti1:20",
		"1Ti2:1",
		"1Ti2:2",
		"1Ti2:3",
		"1Ti2:4",
		"1Ti2:5",
		"1Ti2:6",
		"1Ti2:7",
		"1Ti2:8",
		"1Ti2:9",
		"1Ti2:10",
		"1Ti2:11",
		"1Ti2:12",
		"1Ti2:13",
		"1Ti2:14",
		"1Ti2:15",
		"1Ti3:1",
		"1Ti3:2",
		"1Ti3:3",
		"1Ti3:4",
		"1Ti3:5",
		"1Ti3:6",
		"1Ti3:7",
		"1Ti3:8",
		"1Ti3:9",
		"1Ti3:10",
		"1Ti3:11",
		"1Ti3:12",
		"1Ti3:13",
		"1Ti3:14",
		"1Ti3:15",
		"1Ti3:16",
		"1Ti4:1",
		"1Ti4:2",
		"1Ti4:3",
		"1Ti4:4",
		"1Ti4:5",
		"1Ti4:6",
		"1Ti4:7",
		"1Ti4:8",
		"1Ti4:9",
		"1Ti4:10",
		"1Ti4:11",
		"1Ti4:12",
		"1Ti4:13",
		"1Ti4:14",
		"1Ti4:15",
		"1Ti4:16",
		"1Ti5:1",
		"1Ti5:2",
		"1Ti5:3",
		"1Ti5:4",
		"1Ti5:5",
		"1Ti5:6",
		"1Ti5:7",
		"1Ti5:8",
		"1Ti5:9",
		"1Ti5:10",
		"1Ti5:11",
		"1Ti5:12",
		"1Ti5:13",
		"1Ti5:14",
		"1Ti5:15",
		"1Ti5:16",
		"1Ti5:17",
		"1Ti5:18",
		"1Ti5:19",
		"1Ti5:20",
		"1Ti5:21",
		"1Ti5:22",
		"1Ti5:23",
		"1Ti5:24",
		"1Ti5:25",
		"1Ti6:1",
		"1Ti6:2",
		"1Ti6:3",
		"1Ti6:4",
		"1Ti6:5",
		"1Ti6:6",
		"1Ti6:7",
		"1Ti6:8",
		"1Ti6:9",
		"1Ti6:10",
		"1Ti6:11",
		"1Ti6:12",
		"1Ti6:13",
		"1Ti6:14",
		"1Ti6:15",
		"1Ti6:16",
		"1Ti6:17",
		"1Ti6:18",
		"1Ti6:19",
		"1Ti6:20",
		"1Ti6:21",
		"2Ti1:1",
		"2Ti1:2",
		"2Ti1:3",
		"2Ti1:4",
		"2Ti1:5",
		"2Ti1:6",
		"2Ti1:7",
		"2Ti1:8",
		"2Ti1:9",
		"2Ti1:10",
		"2Ti1:11",
		"2Ti1:12",
		"2Ti1:13",
		"2Ti1:14",
		"2Ti1:15",
		"2Ti1:16",
		"2Ti1:17",
		"2Ti1:18",
		"2Ti2:1",
		"2Ti2:2",
		"2Ti2:3",
		"2Ti2:4",
		"2Ti2:5",
		"2Ti2:6",
		"2Ti2:7",
		"2Ti2:8",
		"2Ti2:9",
		"2Ti2:10",
		"2Ti2:11",
		"2Ti2:12",
		"2Ti2:13",
		"2Ti2:14",
		"2Ti2:15",
		"2Ti2:16",
		"2Ti2:17",
		"2Ti2:18",
		"2Ti2:19",
		"2Ti2:20",
		"2Ti2:21",
		"2Ti2:22",
		"2Ti2:23",
		"2Ti2:24",
		"2Ti2:25",
		"2Ti2:26",
		"2Ti3:1",
		"2Ti3:2",
		"2Ti3:3",
		"2Ti3:4",
		"2Ti3:5",
		"2Ti3:6",
		"2Ti3:7",
		"2Ti3:8",
		"2Ti3:9",
		"2Ti3:10",
		"2Ti3:11",
		"2Ti3:12",
		"2Ti3:13",
		"2Ti3:14",
		"2Ti3:15",
		"2Ti3:16",
		"2Ti3:17",
		"2Ti4:1",
		"2Ti4:2",
		"2Ti4:3",
		"2Ti4:4",
		"2Ti4:5",
		"2Ti4:6",
		"2Ti4:7",
		"2Ti4:8",
		"2Ti4:9",
		"2Ti4:10",
		"2Ti4:11",
		"2Ti4:12",
		"2Ti4:13",
		"2Ti4:14",
		"2Ti4:15",
		"2Ti4:16",
		"2Ti4:17",
		"2Ti4:18",
		"2Ti4:19",
		"2Ti4:20",
		"2Ti4:21",
		"2Ti4:22",
		"Tit1:1",
		"Tit1:2",
		"Tit1:3",
		"Tit1:4",
		"Tit1:5",
		"Tit1:6",
		"Tit1:7",
		"Tit1:8",
		"Tit1:9",
		"Tit1:10",
		"Tit1:11",
		"Tit1:12",
		"Tit1:13",
		"Tit1:14",
		"Tit1:15",
		"Tit1:16",
		"Tit2:1",
		"Tit2:2",
		"Tit2:3",
		"Tit2:4",
		"Tit2:5",
		"Tit2:6",
		"Tit2:7",
		"Tit2:8",
		"Tit2:9",
		"Tit2:10",
		"Tit2:11",
		"Tit2:12",
		"Tit2:13",
		"Tit2:14",
		"Tit2:15",
		"Tit3:1",
		"Tit3:2",
		"Tit3:3",
		"Tit3:4",
		"Tit3:5",
		"Tit3:6",
		"Tit3:7",
		"Tit3:8",
		"Tit3:9",
		"Tit3:10",
		"Tit3:11",
		"Tit3:12",
		"Tit3:13",
		"Tit3:14",
		"Tit3:15",
		"1Pe1:1",
		"1Pe1:2",
		"1Pe1:3",
		"1Pe1:4",
		"1Pe1:5",
		"1Pe1:6",
		"1Pe1:7",
		"1Pe1:8",
		"1Pe1:9",
		"1Pe1:10",
		"1Pe1:11",
		"1Pe1:12",
		"1Pe1:13",
		"1Pe1:14",
		"1Pe1:15",
		"1Pe1:16",
		"1Pe1:17",
		"1Pe1:18",
		"1Pe1:19",
		"1Pe1:20",
		"1Pe1:21",
		"1Pe1:22",
		"1Pe1:23",
		"1Pe1:24",
		"1Pe1:25",
		"1Pe2:1",
		"1Pe2:2",
		"1Pe2:3",
		"1Pe2:4",
		"1Pe2:5",
		"1Pe2:6",
		"1Pe2:7",
		"1Pe2:8",
		"1Pe2:9",
		"1Pe2:10",
		"1Pe2:11",
		"1Pe2:12",
		"1Pe2:13",
		"1Pe2:14",
		"1Pe2:15",
		"1Pe2:16",
		"1Pe2:17",
		"1Pe2:18",
		"1Pe2:19",
		"1Pe2:20",
		"1Pe2:21",
		"1Pe2:22",
		"1Pe2:23",
		"1Pe2:24",
		"1Pe2:25",
		"1Pe3:1",
		"1Pe3:2",
		"1Pe3:3",
		"1Pe3:4",
		"1Pe3:5",
		"1Pe3:6",
		"1Pe3:7",
		"1Pe3:8",
		"1Pe3:9",
		"1Pe3:10",
		"1Pe3:11",
		"1Pe3:12",
		"1Pe3:13",
		"1Pe3:14",
		"1Pe3:15",
		"1Pe3:16",
		"1Pe3:17",
		"1Pe3:18",
		"1Pe3:19",
		"1Pe3:20",
		"1Pe3:21",
		"1Pe3:22",
		"1Pe4:1",
		"1Pe4:2",
		"1Pe4:3",
		"1Pe4:4",
		"1Pe4:5",
		"1Pe4:6",
		"1Pe4:7",
		"1Pe4:8",
		"1Pe4:9",
		"1Pe4:10",
		"1Pe4:11",
		"1Pe4:12",
		"1Pe4:13",
		"1Pe4:14",
		"1Pe4:15",
		"1Pe4:16",
		"1Pe4:17",
		"1Pe4:18",
		"1Pe4:19",
		"1Pe5:1",
		"1Pe5:2",
		"1Pe5:3",
		"1Pe5:4",
		"1Pe5:5",
		"1Pe5:6",
		"1Pe5:7",
		"1Pe5:8",
		"1Pe5:9",
		"1Pe5:10",
		"1Pe5:11",
		"1Pe5:12",
		"1Pe5:13",
		"1Pe5:14",
		"2Pe1:1",
		"2Pe1:2",
		"2Pe1:3",
		"2Pe1:4",
		"2Pe1:5",
		"2Pe1:6",
		"2Pe1:7",
		"2Pe1:8",
		"2Pe1:9",
		"2Pe1:10",
		"2Pe1:11",
		"2Pe1:12",
		"2Pe1:13",
		"2Pe1:14",
		"2Pe1:15",
		"2Pe1:16",
		"2Pe1:17",
		"2Pe1:18",
		"2Pe1:19",
		"2Pe1:20",
		"2Pe1:21",
		"2Pe2:1",
		"2Pe2:2",
		"2Pe2:3",
		"2Pe2:4",
		"2Pe2:5",
		"2Pe2:6",
		"2Pe2:7",
		"2Pe2:8",
		"2Pe2:9",
		"2Pe2:10",
		"2Pe2:11",
		"2Pe2:12",
		"2Pe2:13",
		"2Pe2:14",
		"2Pe2:15",
		"2Pe2:16",
		"2Pe2:17",
		"2Pe2:18",
		"2Pe2:19",
		"2Pe2:20",
		"2Pe2:21",
		"2Pe2:22",
		"2Pe3:1",
		"2Pe3:2",
		"2Pe3:3",
		"2Pe3:4",
		"2Pe3:5",
		"2Pe3:6",
		"2Pe3:7",
		"2Pe3:8",
		"2Pe3:9",
		"2Pe3:10",
		"2Pe3:11",
		"2Pe3:12",
		"2Pe3:13",
		"2Pe3:14",
		"2Pe3:15",
		"2Pe3:16",
		"2Pe3:17",
		"2Pe3:18"
	 ];

	var Verses = [
		"Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians which is in God the Father and in the Lord Jesus Christ: Grace be unto you, and peace, from God our Father, and the Lord Jesus Christ.",
		"We give thanks to God always for you all, making mention of you in our prayers;",
		"Remembering without ceasing your work of faith, and labour of love, and patience of hope in our Lord Jesus Christ, in the sight of God and our Father;",
		"Knowing, brethren beloved, your election of God.",
		"For our gospel came not unto you in word only, but also in power, and in the Holy Ghost, and in much assurance; as ye know what manner of men we were among you for your sake.",
		"And ye became followers of us, and of the Lord, having received the word in much affliction, with joy of the Holy Ghost:",
		"So that ye were ensamples to all that believe in Macedonia and Achaia.",
		"For from you sounded out the word of the Lord not only in Macedonia and Achaia, but also in every place your faith to God-ward is spread abroad; so that we need not to speak any thing.",
		"For they themselves show of us what manner of entering in we had unto you, and how ye turned to God from idols to serve the living and true God;",
		"And to wait for his Son from heaven, whom he raised from the dead, even Jesus, which delivered us from the wrath to come.",
		"For yourselves, brethren, know our entrance in unto you, that it was not in vain:",
		"But even after that we had suffered before, and were shamefully entreated, as ye know, at Philippi, we were bold in our God to speak unto you the gospel of God with much contention.",
		"For our exhortation was not of deceit, nor of uncleanness, nor in guile:",
		"But as we were allowed of God to be put in trust with the gospel, even so we speak; not as pleasing men, but God, which trieth our hearts.",
		"For neither at any time used we flattering words, as ye know, nor a cloak of covetousness; God is witness:",
		"Nor of men sought we glory, neither of you, nor yet of others, when we might have been burdensome, as the apostles of Christ.",
		"But we were gentle among you, even as a nurse cherisheth her children:",
		"So being affectionately desirous of you, we were willing to have imparted unto you, not the gospel of God only, but also our own souls, because ye were dear unto us.",
		"For ye remember, brethren, our labour and travail: for labouring night and day, because we would not be chargeable unto any of you, we preached unto you the gospel of God.",
		"Ye are witnesses, and God also, how holily and justly and unblameably we behaved ourselves among you that believe:",
		"As ye know how we exhorted and comforted and charged every one of you, as a father doth his children,",
		"That ye would walk worthy of God, who hath called you unto his kingdom and glory.",
		"For this cause also thank we God without ceasing, because, when ye received the word of God which ye heard of us, ye received it not as the word of men, but as it is in truth, the word of God, which effectually worketh also in you that believe.",
		"For ye, brethren, became followers of the churches of God which in Judaea are in Christ Jesus: for ye also have suffered like things of your own countrymen, even as they have of the Jews:",
		"Who both killed the Lord Jesus, and their own prophets, and have persecuted us; and they please not God, and are contrary to all men:",
		"Forbidding us to speak to the Gentiles that they might be saved, to fill up their sins alway: for the wrath is come upon them to the uttermost.",
		"But we, brethren, being taken from you for a short time in presence, not in heart, endeavoured the more abundantly to see your face with great desire.",
		"Wherefore we would have come unto you, even I Paul, once and again; but Satan hindered us.",
		"For what is our hope, or joy, or crown of rejoicing? Are not even ye in the presence of our Lord Jesus Christ at his coming?",
		"For ye are our glory and joy.",
		"Wherefore when we could no longer forbear, we thought it good to be left at Athens alone;",
		"And sent Timotheus, our brother, and minister of God, and our fellowlabourer in the gospel of Christ, to establish you, and to comfort you concerning your faith:",
		"That no man should be moved by these afflictions: for yourselves know that we are appointed thereunto.",
		"For verily, when we were with you, we told you before that we should suffer tribulation; even as it came to pass, and ye know.",
		"For this cause, when I could no longer forbear, I sent to know your faith, lest by some means the tempter have tempted you, and our labour be in vain.",
		"But now when Timotheus came from you unto us, and brought us good tidings of your faith and charity, and that ye have good remembrance of us always, desiring greatly to see us, as we also to see you:",
		"Therefore, brethren, we were comforted over you in all our affliction and distress by your faith:",
		"For now we live, if ye stand fast in the Lord.",
		"For what thanks can we render to God again for you, for all the joy wherewith we joy for your sakes before our God;",
		"Night and day praying exceedingly that we might see your face, and might perfect that which is lacking in your faith?",
		"Now God himself and our Father, and our Lord Jesus Christ, direct our way unto you.",
		"And the Lord make you to increase and abound in love one toward another, and toward all men, even as we do toward you:",
		"To the end he may stablish your hearts unblameable in holiness before God, even our Father, at the coming of our Lord Jesus Christ with all his saints.",
		"Furthermore then we beseech you, brethren, and exhort you by the Lord Jesus, that as ye have received of us how ye ought to walk and to please God, so ye would abound more and more.",
		"For ye know what commandments we gave you by the Lord Jesus.",
		"For this is the will of God, even your sanctification, that ye should abstain from fornication:",
		"That every one of you should know how to possess his vessel in sanctification and honour;",
		"Not in the lust of concupiscence, even as the Gentiles which know not God:",
		"That no man go beyond and defraud his brother in any matter: because that the Lord is the avenger of all such, as we also have forewarned you and testified.",
		"For God hath not called us unto uncleanness, but unto holiness.",
		"He therefore that despiseth, despiseth not man, but God, who hath also given unto us his holy Spirit.",
		"But as touching brotherly love ye need not that I write unto you: for ye yourselves are taught of God to love one another.",
		"And indeed ye do it toward all the brethren which are in all Macedonia: but we beseech you, brethren, that ye increase more and more;",
		"And that ye study to be quiet, and to do your own business, and to work with your own hands, as we commanded you;",
		"That ye may walk honestly toward them that are without, and that ye may have lack of nothing.",
		"But I would not have you to be ignorant, brethren, concerning them which are asleep, that ye sorrow not, even as others which have no hope.",
		"For if we believe that Jesus died and rose again, even so them also which sleep in Jesus will God bring with him.",
		"For this we say unto you by the word of the Lord, that we which are alive and remain unto the coming of the Lord shall not prevent them which are asleep.",
		"For the Lord himself shall descend from heaven with a shout, with the voice of the archangel, and with the trump of God: and the dead in Christ shall rise first:",
		"Then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air: and so shall we ever be with the Lord.",
		"Wherefore comfort one another with these words.",
		"But of the times and the seasons, brethren, ye have no need that I write unto you.",
		"For yourselves know perfectly that the day of the Lord so cometh as a thief in the night.",
		"For when they shall say, Peace and safety; then sudden destruction cometh upon them, as travail upon a woman with child; and they shall not escape.",
		"But ye, brethren, are not in darkness, that that day should overtake you as a thief.",
		"Ye are all the children of light, and the children of the day: we are not of the night, nor of darkness.",
		"Therefore let us not sleep, as do others; but let us watch and be sober.",
		"For they that sleep sleep in the night; and they that be drunken are drunken in the night.",
		"But let us, who are of the day, be sober, putting on the breastplate of faith and love; and for an helmet, the hope of salvation.",
		"For God hath not appointed us to wrath, but to obtain salvation by our Lord Jesus Christ,",
		"Who died for us, that, whether we wake or sleep, we should live together with him.",
		"Wherefore comfort yourselves together, and edify one another, even as also ye do.",
		"And we beseech you, brethren, to know them which labour among you, and are over you in the Lord, and admonish you;",
		"And to esteem them very highly in love for their work's sake. And be at peace among yourselves.",
		"Now we exhort you, brethren, warn them that are unruly, comfort the feebleminded, support the weak, be patient toward all men.",
		"See that none render evil for evil unto any man; but ever follow that which is good, both among yourselves, and to all men.",
		"Rejoice evermore.",
		"Pray without ceasing.",
		"In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
		"Quench not the Spirit.",
		"Despise not prophesyings.",
		"Prove all things; hold fast that which is good.",
		"Abstain from all appearance of evil.",
		"And the very God of peace sanctify you wholly; and I pray God your whole spirit and soul and body be preserved blameless unto the coming of our Lord Jesus Christ.",
		"Faithful is he that calleth you, who also will do it.",
		"Brethren, pray for us.",
		"Greet all the brethren with an holy kiss.",
		"I charge you by the Lord that this epistle be read unto all the holy brethren.",
		"The grace of our Lord Jesus Christ be with you. Amen.",
		"Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians in God our Father and the Lord Jesus Christ:",
		"Grace unto you, and peace, from God our Father and the Lord Jesus Christ.",
		"We are bound to thank God always for you, brethren, as it is meet, because that your faith groweth exceedingly, and the charity of every one of you all toward each other aboundeth;",
		"So that we ourselves glory in you in the churches of God for your patience and faith in all your persecutions and tribulations that ye endure:",
		"Which is a manifest token of the righteous judgment of God, that ye may be counted worthy of the kingdom of God, for which ye also suffer:",
		"Seeing it is a righteous thing with God to recompense tribulation to them that trouble you;",
		"And to you who are troubled rest with us, when the Lord Jesus shall be revealed from heaven with his mighty angels,",
		"In flaming fire taking vengeance on them that know not God, and that obey not the gospel of our Lord Jesus Christ:",
		"Who shall be punished with everlasting destruction from the presence of the Lord, and from the glory of his power;",
		"When he shall come to be glorified in his saints, and to be admired in all them that believe (because our testimony among you was believed) in that day.",
		"Wherefore also we pray always for you, that our God would count you worthy of this calling, and fulfil all the good pleasure of his goodness, and the work of faith with power:",
		"That the name of our Lord Jesus Christ may be glorified in you, and ye in him, according to the grace of our God and the Lord Jesus Christ.",
		"Now we beseech you, brethren, by the coming of our Lord Jesus Christ, and by our gathering together unto him,",
		"That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand.",
		"Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition;",
		"Who opposeth and exalteth himself above all that is called God, or that is worshipped; so that he as God sitteth in the temple of God, showing himself that he is God.",
		"Remember ye not, that, when I was yet with you, I told you these things?",
		"And now ye know what withholdeth that he might be revealed in his time.",
		"For the mystery of iniquity doth already work: only he who now letteth will let, until he be taken out of the way.",
		"And then shall that Wicked be revealed, whom the Lord shall consume with the spirit of his mouth, and shall destroy with the brightness of his coming:",
		"Even him, whose coming is after the working of Satan with all power and signs and lying wonders,",
		"And with all deceivableness of unrighteousness in them that perish; because they received not the love of the truth, that they might be saved.",
		"And for this cause God shall send them strong delusion, that they should believe a lie:",
		"That they all might be damned who believed not the truth, but had pleasure in unrighteousness.",
		"But we are bound to give thanks alway to God for you, brethren beloved of the Lord, because God hath from the beginning chosen you to salvation through sanctification of the Spirit and belief of the truth:",
		"Whereunto he called you by our gospel, to the obtaining of the glory of our Lord Jesus Christ.",
		"Therefore, brethren, stand fast, and hold the traditions which ye have been taught, whether by word, or our epistle.",
		"Now our Lord Jesus Christ himself, and God, even our Father, which hath loved us, and hath given us everlasting consolation and good hope through grace,",
		"Comfort your hearts, and stablish you in every good word and work.",
		"Finally, brethren, pray for us, that the word of the Lord may have free course, and be glorified, even as it is with you:",
		"And that we may be delivered from unreasonable and wicked men: for all men have not faith.",
		"But the Lord is faithful, who shall stablish you, and keep you from evil.",
		"And we have confidence in the Lord touching you, that ye both do and will do the things which we command you.",
		"And the Lord direct your hearts into the love of God, and into the patient waiting for Christ.",
		"Now we command you, brethren, in the name of our Lord Jesus Christ, that ye withdraw yourselves from every brother that walketh disorderly, and not after the tradition which he received of us.",
		"For yourselves know how ye ought to follow us: for we behaved not ourselves disorderly among you;",
		"Neither did we eat any man's bread for nought; but wrought with labour and travail night and day, that we might not be chargeable to any of you:",
		"Not because we have not power, but to make ourselves an ensample unto you to follow us.",
		"For even when we were with you, this we commanded you, that if any would not work, neither should he eat.",
		"For we hear that there are some which walk among you disorderly, working not at all, but are busybodies.",
		"Now them that are such we command and exhort by our Lord Jesus Christ, that with quietness they work, and eat their own bread.",
		"But ye, brethren, be not weary in well doing.",
		"And if any man obey not our word by this epistle, note that man, and have no company with him, that he may be ashamed.",
		"Yet count him not as an enemy, but admonish him as a brother.",
		"Now the Lord of peace himself give you peace always by all means. The Lord be with you all.",
		"The salutation of Paul with mine own hand, which is the token in every epistle: so I write.",
		"The grace of our Lord Jesus Christ be with you all. Amen.",
		"Paul, an apostle of Jesus Christ by the commandment of God our Saviour, and Lord Jesus Christ, which is our hope;",
		"Unto Timothy, my own son in the faith: Grace, mercy, and peace, from God our Father and Jesus Christ our Lord.",
		"As I besought thee to abide still at Ephesus, when I went into Macedonia, that thou mightest charge some that they teach no other doctrine,",
		"Neither give heed to fables and endless genealogies, which minister questions, rather than godly edifying which is in faith: so do.",
		"Now the end of the commandment is charity out of a pure heart, and of a good conscience, and of faith unfeigned:",
		"From which some having swerved have turned aside unto vain jangling;",
		"Desiring to be teachers of the law; understanding neither what they say, nor whereof they affirm.",
		"But we know that the law is good, if a man use it lawfully;",
		"Knowing this, that the law is not made for a righteous man, but for the lawless and disobedient, for the ungodly and for sinners, for unholy and profane, for murderers of fathers and murderers of mothers, for manslayers,",
		"For whoremongers, for them that defile themselves with mankind, for menstealers, for liars, for perjured persons, and if there be any other thing that is contrary to sound doctrine;",
		"According to the glorious gospel of the blessed God, which was committed to my trust.",
		"And I thank Christ Jesus our Lord, who hath enabled me, for that he counted me faithful, putting me into the ministry;",
		"Who was before a blasphemer, and a persecutor, and injurious: but I obtained mercy, because I did it ignorantly in unbelief.",
		"And the grace of our Lord was exceeding abundant with faith and love which is in Christ Jesus.",
		"This is a faithful saying, and worthy of all acceptation, that Christ Jesus came into the world to save sinners; of whom I am chief.",
		"Howbeit for this cause I obtained mercy, that in me first Jesus Christ might show forth all longsuffering, for a pattern to them which should hereafter believe on him to life everlasting.",
		"Now unto the King eternal, immortal, invisible, the only wise God, be honour and glory for ever and ever. Amen.",
		"This charge I commit unto thee, son Timothy, according to the prophecies which went before on thee, that thou by them mightest war a good warfare;",
		"Holding faith, and a good conscience; which some having put away concerning faith have made shipwreck:",
		"Of whom is Hymenaeus and Alexander; whom I have delivered unto Satan, that they may learn not to blaspheme.",
		"I exhort therefore, that, first of all, supplications, prayers, intercessions, and giving of thanks, be made for all men;",
		"For kings, and for all that are in authority; that we may lead a quiet and peaceable life in all godliness and honesty.",
		"For this is good and acceptable in the sight of God our Saviour;",
		"Who will have all men to be saved, and to come unto the knowledge of the truth.",
		"For there is one God, and one mediator between God and men, the man Christ Jesus;",
		"Who gave himself a ransom for all, to be testified in due time.",
		"Whereunto I am ordained a preacher, and an apostle, (I speak the truth in Christ, and lie not;) a teacher of the Gentiles in faith and verity.",
		"I will therefore that men pray every where, lifting up holy hands, without wrath and doubting.",
		"In like manner also, that women adorn themselves in modest apparel, with shamefacedness and sobriety; not with broided hair, or gold, or pearls, or costly array;",
		"But (which becometh women professing godliness) with good works.",
		"Let the woman learn in silence with all subjection.",
		"But I suffer not a woman to teach, nor to usurp authority over the man, but to be in silence.",
		"For Adam was first formed, then Eve.",
		"And Adam was not deceived, but the woman being deceived was in the transgression.",
		"Notwithstanding she shall be saved in childbearing, if they continue in faith and charity and holiness with sobriety.",
		"This is a true saying, If a man desire the office of a bishop, he desireth a good work.",
		"A bishop then must be blameless, the husband of one wife, vigilant, sober, of good behaviour, given to hospitality, apt to teach;",
		"Not given to wine, no striker, not greedy of filthy lucre; but patient, not a brawler, not covetous;",
		"One that ruleth well his own house, having his children in subjection with all gravity;",
		"(For if a man know not how to rule his own house, how shall he take care of the church of God?)",
		"Not a novice, lest being lifted up with pride he fall into the condemnation of the devil.",
		"Moreover he must have a good report of them which are without; lest he fall into reproach and the snare of the devil.",
		"Likewise must the deacons be grave, not doubletongued, not given to much wine, not greedy of filthy lucre;",
		"Holding the mystery of the faith in a pure conscience.",
		"And let these also first be proved; then let them use the office of a deacon, being found blameless.",
		"Even so must their wives be grave, not slanderers, sober, faithful in all things.",
		"Let the deacons be the husbands of one wife, ruling their children and their own houses well.",
		"For they that have used the office of a deacon well purchase to themselves a good degree, and great boldness in the faith which is in Christ Jesus.",
		"These things write I unto thee, hoping to come unto thee shortly:",
		"But if I tarry long, that thou mayest know how thou oughtest to behave thyself in the house of God, which is the church of the living God, the pillar and ground of the truth.",
		"And without controversy great is the mystery of godliness: God was manifest in the flesh, justified in the Spirit, seen of angels, preached unto the Gentiles, believed on in the world, received up into glory.",
		"Now the Spirit speaketh expressly, that in the latter times some shall depart from the faith, giving heed to seducing spirits, and doctrines of devils;",
		"Speaking lies in hypocrisy; having their conscience seared with a hot iron;",
		"Forbidding to marry, and commanding to abstain from meats, which God hath created to be received with thanksgiving of them which believe and know the truth.",
		"For every creature of God is good, and nothing to be refused, if it be received with thanksgiving:",
		"For it is sanctified by the word of God and prayer.",
		"If thou put the brethren in remembrance of these things, thou shalt be a good minister of Jesus Christ, nourished up in the words of faith and of good doctrine, whereunto thou hast attained.",
		"But refuse profane and old wives' fables, and exercise thyself rather unto godliness.",
		"For bodily exercise profiteth little: but godliness is profitable unto all things, having promise of the life that now is, and of that which is to come.",
		"This is a faithful saying and worthy of all acceptation.",
		"For therefore we both labour and suffer reproach, because we trust in the living God, who is the Saviour of all men, specially of those that believe.",
		"These things command and teach.",
		"Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.",
		"Till I come, give attendance to reading, to exhortation, to doctrine.",
		"Neglect not the gift that is in thee, which was given thee by prophecy, with the laying on of the hands of the presbytery.",
		"Meditate upon these things; give thyself wholly to them; that thy profiting may appear to all.",
		"Take heed unto thyself, and unto the doctrine; continue in them: for in doing this thou shalt both save thyself, and them that hear thee.",
		"Rebuke not an elder, but entreat him as a father; and the younger men as brethren;",
		"The elder women as mothers; the younger as sisters, with all purity.",
		"Honour widows that are widows indeed.",
		"But if any widow have children or nephews, let them learn first to show piety at home, and to requite their parents: for that is good and acceptable before God.",
		"Now she that is a widow indeed, and desolate, trusteth in God, and continueth in supplications and prayers night and day.",
		"But she that liveth in pleasure is dead while she liveth.",
		"And these things give in charge, that they may be blameless.",
		"But if any provide not for his own, and specially for those of his own house, he hath denied the faith, and is worse than an infidel.",
		"Let not a widow be taken into the number under threescore years old, having been the wife of one man,",
		"Well reported of for good works; if she have brought up children, if she have lodged strangers, if she have washed the saints' feet, if she have relieved the afflicted, if she have diligently followed every good work.",
		"But the younger widows refuse: for when they have begun to wax wanton against Christ, they will marry;",
		"Having damnation, because they have cast off their first faith.",
		"And withal they learn to be idle, wandering about from house to house; and not only idle, but tattlers also and busybodies, speaking things which they ought not.",
		"I will therefore that the younger women marry, bear children, guide the house, give none occasion to the adversary to speak reproachfully.",
		"For some are already turned aside after Satan.",
		"If any man or woman that believeth have widows, let them relieve them, and let not the church be charged; that it may relieve them that are widows indeed.",
		"Let the elders that rule well be counted worthy of double honour, especially they who labour in the word and doctrine.",
		"For the scripture saith, Thou shalt not muzzle the ox that treadeth out the corn. And, The labourer is worthy of his reward.",
		"Against an elder receive not an accusation, but before two or three witnesses.",
		"Them that sin rebuke before all, that others also may fear.",
		"I charge thee before God, and the Lord Jesus Christ, and the elect angels, that thou observe these things without preferring one before another, doing nothing by partiality.",
		"Lay hands suddenly on no man, neither be partaker of other men's sins: keep thyself pure.",
		"Drink no longer water, but use a little wine for thy stomach's sake and thine often infirmities.",
		"Some men's sins are open beforehand, going before to judgment; and some men they follow after.",
		"Likewise also the good works of some are manifest beforehand; and they that are otherwise cannot be hid.",
		"Let as many servants as are under the yoke count their own masters worthy of all honour, that the name of God and his doctrine be not blasphemed.",
		"And they that have believing masters, let them not despise them, because they are brethren; but rather do them service, because they are faithful and beloved, partakers of the benefit. These things teach and exhort.",
		"If any man teach otherwise, and consent not to wholesome words, even the words of our Lord Jesus Christ, and to the doctrine which is according to godliness;",
		"He is proud, knowing nothing, but doting about questions and strifes of words, whereof cometh envy, strife, railings, evil surmisings,",
		"Perverse disputings of men of corrupt minds, and destitute of the truth, supposing that gain is godliness: from such withdraw thyself.",
		"But godliness with contentment is great gain.",
		"For we brought nothing into this world, and it is certain we can carry nothing out.",
		"And having food and raiment let us be therewith content.",
		"But they that will be rich fall into temptation and a snare, and into many foolish and hurtful lusts, which drown men in destruction and perdition.",
		"For the love of money is the root of all evil: which while some coveted after, they have erred from the faith, and pierced themselves through with many sorrows.",
		"But thou, O man of God, flee these things; and follow after righteousness, godliness, faith, love, patience, meekness.",
		"Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses.",
		"I give thee charge in the sight of God, who quickeneth all things, and before Christ Jesus, who before Pontius Pilate witnessed a good confession;",
		"That thou keep this commandment without spot, unrebukeable, until the appearing of our Lord Jesus Christ:",
		"Which in his times he shall show, who is the blessed and only Potentate, the King of kings, and Lord of lords;",
		"Who only hath immortality, dwelling in the light which no man can approach unto; whom no man hath seen, nor can see: to whom be honour and power everlasting. Amen.",
		"Charge them that are rich in this world, that they be not highminded, nor trust in uncertain riches, but in the living God, who giveth us richly all things to enjoy;",
		"That they do good, that they be rich in good works, ready to distribute, willing to communicate;",
		"Laying up in store for themselves a good foundation against the time to come, that they may lay hold on eternal life.",
		"O Timothy, keep that which is committed to thy trust, avoiding profane and vain babblings, and oppositions of science falsely so called:",
		"Which some professing have erred concerning the faith. Grace be with thee. Amen.",
		"Paul, an apostle of Jesus Christ by the will of God, according to the promise of life which is in Christ Jesus,",
		"To Timothy, my dearly beloved son: Grace, mercy, and peace, from God the Father and Christ Jesus our Lord.",
		"I thank God, whom I serve from my forefathers with pure conscience, that without ceasing I have remembrance of thee in my prayers night and day;",
		"Greatly desiring to see thee, being mindful of thy tears, that I may be filled with joy;",
		"When I call to remembrance the unfeigned faith that is in thee, which dwelt first in thy grandmother Lois, and thy mother Eunice; and I am persuaded that in thee also.",
		"Wherefore I put thee in remembrance that thou stir up the gift of God, which is in thee by the putting on of my hands.",
		"For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
		"Be not thou therefore ashamed of the testimony of our Lord, nor of me his prisoner: but be thou partaker of the afflictions of the gospel according to the power of God;",
		"Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began,",
		"But is now made manifest by the appearing of our Saviour Jesus Christ, who hath abolished death, and hath brought life and immortality to light through the gospel:",
		"Whereunto I am appointed a preacher, and an apostle, and a teacher of the Gentiles.",
		"For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day.",
		"Hold fast the form of sound words, which thou hast heard of me, in faith and love which is in Christ Jesus.",
		"That good thing which was committed unto thee keep by the Holy Ghost which dwelleth in us.",
		"This thou knowest, that all they which are in Asia be turned away from me; of whom are Phygellus and Hermogenes.",
		"The Lord give mercy unto the house of Onesiphorus; for he oft refreshed me, and was not ashamed of my chain:",
		"But, when he was in Rome, he sought me out very diligently, and found me.",
		"The Lord grant unto him that he may find mercy of the Lord in that day: and in how many things he ministered unto me at Ephesus, thou knowest very well.",
		"Thou therefore, my son, be strong in the grace that is in Christ Jesus.",
		"And the things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also.",
		"Thou therefore endure hardness, as a good soldier of Jesus Christ.",
		"No man that warreth entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier.",
		"And if a man also strive for masteries, yet is he not crowned, except he strive lawfully.",
		"The husbandman that laboureth must be first partaker of the fruits.",
		"Consider what I say; and the Lord give thee understanding in all things.",
		"Remember that Jesus Christ of the seed of David was raised from the dead according to my gospel:",
		"Wherein I suffer trouble, as an evil doer, even unto bonds; but the word of God is not bound.",
		"Therefore I endure all things for the elect's sakes, that they may also obtain the salvation which is in Christ Jesus with eternal glory.",
		"It is a faithful saying: For if we be dead with him, we shall also live with him:",
		"If we suffer, we shall also reign with him: if we deny him, he also will deny us:",
		"If we believe not, yet he abideth faithful: he cannot deny himself.",
		"Of these things put them in remembrance, charging them before the Lord that they strive not about words to no profit, but to the subverting of the hearers.",
		"Study to show thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth.",
		"But shun profane and vain babblings: for they will increase unto more ungodliness.",
		"And their word will eat as doth a canker: of whom is Hymenaeus and Philetus;",
		"Who concerning the truth have erred, saying that the resurrection is past already; and overthrow the faith of some.",
		"Nevertheless the foundation of God standeth sure, having this seal, The Lord knoweth them that are his. And, Let every one that nameth the name of Christ depart from iniquity.",
		"But in a great house there are not only vessels of gold and of silver, but also of wood and of earth; and some to honour, and some to dishonour.",
		"If a man therefore purge himself from these, he shall be a vessel unto honour, sanctified, and meet for the master's use, and prepared unto every good work.",
		"Flee also youthful lusts: but follow righteousness, faith, charity, peace, with them that call on the Lord out of a pure heart.",
		"But foolish and unlearned questions avoid, knowing that they do gender strifes.",
		"And the servant of the Lord must not strive; but be gentle unto all men, apt to teach, patient,",
		"In meekness instructing those that oppose themselves; if God peradventure will give them repentance to the acknowledging of the truth;",
		"And that they may recover themselves out of the snare of the devil, who are taken captive by him at his will.",
		"This know also, that in the last days perilous times shall come.",
		"For men shall be lovers of their own selves, covetous, boasters, proud, blasphemers, disobedient to parents, unthankful, unholy,",
		"Without natural affection, trucebreakers, false accusers, incontinent, fierce, despisers of those that are good,",
		"Traitors, heady, highminded, lovers of pleasures more than lovers of God;",
		"Having a form of godliness, but denying the power thereof: from such turn away.",
		"For of this sort are they which creep into houses, and lead captive silly women laden with sins, led away with divers lusts,",
		"Ever learning, and never able to come to the knowledge of the truth.",
		"Now as Jannes and Jambres withstood Moses, so do these also resist the truth: men of corrupt minds, reprobate concerning the faith.",
		"But they shall proceed no further: for their folly shall be manifest unto all men, as theirs also was.",
		"But thou hast fully known my doctrine, manner of life, purpose, faith, longsuffering, charity, patience,",
		"Persecutions, afflictions, which came unto me at Antioch, at Iconium, at Lystra; what persecutions I endured: but out of them all the Lord delivered me.",
		"Yea, and all that will live godly in Christ Jesus shall suffer persecution.",
		"But evil men and seducers shall wax worse and worse, deceiving, and being deceived.",
		"But continue thou in the things which thou hast learned and hast been assured of, knowing of whom thou hast learned them;",
		"And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus.",
		"All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:",
		"That the man of God may be perfect, thoroughly furnished unto all good works.",
		"I charge thee therefore before God, and the Lord Jesus Christ, who shall judge the quick and the dead at his appearing and his kingdom;",
		"Preach the word; be instant in season, out of season; reprove, rebuke, exhort with all longsuffering and doctrine.",
		"For the time will come when they will not endure sound doctrine; but after their own lusts shall they heap to themselves teachers, having itching ears;",
		"And they shall turn away their ears from the truth, and shall be turned unto fables.",
		"But watch thou in all things, endure afflictions, do the work of an evangelist, make full proof of thy ministry.",
		"For I am now ready to be offered, and the time of my departure is at hand.",
		"I have fought a good fight, I have finished my course, I have kept the faith:",
		"Henceforth there is laid up for me a crown of righteousness, which the Lord, the righteous judge, shall give me at that day: and not to me only, but unto all them also that love his appearing.",
		"Do thy diligence to come shortly unto me:",
		"For Demas hath forsaken me, having loved this present world, and is departed unto Thessalonica; Crescens to Galatia, Titunto Dalmatia.",
		"Only Luke is with me. Take Mark, and bring him with thee: for he is profitable to me for the ministry.",
		"And Tychicus have I sent to Ephesus.",
		"The cloak that I left at Troas with Carpus, when thou comest, bring with thee, and the books, but especially the parchments.",
		"Alexander the coppersmith did me much evil: the Lord reward him according to his works:",
		"Of whom be thou ware also; for he hath greatly withstood our words.",
		"At my first answer no man stood with me, but all men forsook me: I pray God that it may not be laid to their charge.",
		"Notwithstanding the Lord stood with me, and strengthened me; that by me the preaching might be fully known, and that all the Gentiles might hear: and I was delivered out of the mouth of the lion.",
		"And the Lord shall deliver me from every evil work, and will preserve me unto his heavenly kingdom: to whom be glory for ever and ever. Amen.",
		"Salute Prisca and Aquila, and the household of Onesiphorus.",
		"Erastus abode at Corinth: but Trophimus have I left at Miletum sick.",
		"Do thy diligence to come before winter. Eubulus greeteth thee, and Pudens, and Linus, and Claudia, and all the brethren.",
		"The Lord Jesus Christ be with thy spirit. Grace be with you. Amen.",
		"Paul, a servant of God, and an apostle of Jesus Christ, according to the faith of God's elect, and the acknowledging of the truth which is after godliness;",
		"In hope of eternal life, which God, that cannot lie, promised before the world began;",
		"But hath in due times manifested his word through preaching, which is committed unto me according to the commandment of God our Saviour;",
		"To Titus, mine own son after the common faith: Grace, mercy, and peace, from God the Father and the Lord Jesus Christ our Saviour.",
		"For this cause left I thee in Crete, that thou shouldest set in order the things that are wanting, and ordain elders in every city, as I had appointed thee:",
		"If any be blameless, the husband of one wife, having faithful children not accused of riot or unruly.",
		"For a bishop must be blameless, as the steward of God; not selfwilled, not soon angry, not given to wine, no striker, not given to filthy lucre;",
		"But a lover of hospitality, a lover of good men, sober, just, holy, temperate;",
		"Holding fast the faithful word as he hath been taught, that he may be able by sound doctrine both to exhort and to convince the gainsayers.",
		"For there are many unruly and vain talkers and deceivers, specially they of the circumcision:",
		"Whose mouths must be stopped, who subvert whole houses, teaching things which they ought not, for filthy lucre's sake.",
		"One of themselves, even a prophet of their own, said, The Cretians are alway liars, evil beasts, slow bellies.",
		"This witness is true. Wherefore rebuke them sharply, that they may be sound in the faith;",
		"Not giving heed to Jewish fables, and commandments of men, that turn from the truth.",
		"Unto the pure all things are pure: but unto them that are defiled and unbelieving is nothing pure; but even their mind and conscience is defiled.",
		"They profess that they know God; but in works they deny him, being abominable, and disobedient, and unto every good work reprobate.",
		"But speak thou the things which become sound doctrine:",
		"That the aged men be sober, grave, temperate, sound in faith, in charity, in patience.",
		"The aged women likewise, that they be in behaviour as becometh holiness, not false accusers, not given to much wine, teachers of good things;",
		"That they may teach the young women to be sober, to love their husbands, to love their children,",
		"To be discreet, chaste, keepers at home, good, obedient to their own husbands, that the word of God be not blasphemed.",
		"Young men likewise exhort to be sober minded.",
		"In all things showing thyself a pattern of good works: in doctrine showing uncorruptness, gravity, sincerity,",
		"Sound speech, that cannot be condemned; that he that is of the contrary part may be ashamed, having no evil thing to say of you.",
		"Exhort servants to be obedient unto their own masters, and to please them well in all things; not answering again;",
		"Not purloining, but showing all good fidelity; that they may adorn the doctrine of God our Saviour in all things.",
		"For the grace of God that bringeth salvation hath appeared to all men,",
		"Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world;",
		"Looking for that blessed hope, and the glorious appearing of the great God and our Saviour Jesus Christ;",
		"Who gave himself for us, that he might redeem us from all iniquity, and purify unto himself a peculiar people, zealous of good works.",
		"These things speak, and exhort, and rebuke with all authority. Let no man despise thee.",
		"Put them in mind to be subject to principalities and powers, to obey magistrates, to be ready to every good work,",
		"To speak evil of no man, to be no brawlers, but gentle, showing all meekness unto all men.",
		"For we ourselves also were sometimes foolish, disobedient, deceived, serving divers lusts and pleasures, living in malice and envy, hateful, and hating one another.",
		"But after that the kindness and love of God our Saviour toward man appeared,",
		"Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;",
		"Which he shed on us abundantly through Jesus Christ our Saviour;",
		"That being justified by his grace, we should be made heirs according to the hope of eternal life.",
		"This is a faithful saying, and these things I will that thou affirm constantly, that they which have believed in God might be careful to maintain good works. These things are good and profitable unto men.",
		"But avoid foolish questions, and genealogies, and contentions, and strivings about the law; for they are unprofitable and vain.",
		"A man that is an heretic after the first and second admonition reject;",
		"Knowing that he that is such is subverted, and sinneth, being condemned of himself.",
		"When I shall send Artemas unto thee, or Tychicus, be diligent to come unto me to Nicopolis: for I have determined there to winter.",
		"Bring Zenas the lawyer and Apollos on their journey diligently, that nothing be wanting unto them.",
		"And let ours also learn to maintain good works for necessary uses, that they be not unfruitful.",
		"All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen.",
		"Peter, an apostle of Jesus Christ, to the strangers scattered throughout Pontus, Galatia, Cappadocia, Asia, and Bithynia,",
		"Elect according to the foreknowledge of God the Father, through sanctification of the Spirit, unto obedience and sprinkling of the blood of Jesus Christ: Grace unto you, and peace, be multiplied.",
		"Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead,",
		"To an inheritance incorruptible, and undefiled, and that fadeth not away, reserved in heaven for you,",
		"Who are kept by the power of God through faith unto salvation ready to be revealed in the last time.",
		"Wherein ye greatly rejoice, though now for a season, if need be, ye are in heaviness through manifold temptations:",
		"That the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire, might be found unto praise and honour and glory at the appearing of Jesus Christ:",
		"Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory:",
		"Receiving the end of your faith, even the salvation of your souls.",
		"Of which salvation the prophets have inquired and searched diligently, who prophesied of the grace that should come unto you:",
		"Searching what, or what manner of time the Spirit of Christ which was in them did signify, when it testified beforehand the sufferings of Christ, and the glory that should follow.",
		"Unto whom it was revealed, that not unto themselves, but unto us they did minister the things, which are now reported unto you by them that have preached the gospel unto you with the Holy Ghost sent down from heaven; which things the angels desire to look into.",
		"Wherefore gird up the loins of your mind, be sober, and hope to the end for the grace that is to be brought unto you at the revelation of Jesus Christ;",
		"As obedient children, not fashioning yourselves according to the former lusts in your ignorance:",
		"But as he which hath called you is holy, so be ye holy in all manner of conversation;",
		"Because it is written, Be ye holy; for I am holy.",
		"And if ye call on the Father, who without respect of persons judgeth according to every man's work, pass the time of your sojourning here in fear:",
		"Forasmuch as ye know that ye were not redeemed with corruptible things, as silver and gold, from your vain conversation received by tradition from your fathers;",
		"But with the precious blood of Christ, as of a lamb without blemish and without spot:",
		"Who verily was foreordained before the foundation of the world, but was manifest in these last times for you,",
		"Who by him do believe in God, that raised him up from the dead, and gave him glory; that your faith and hope might be in God.",
		"Seeing ye have purified your souls in obeying the truth through the Spirit unto unfeigned love of the brethren, see that ye love one another with a pure heart fervently:",
		"Being born again, not of corruptible seed, but of incorruptible, by the word of God, which liveth and abideth for ever.",
		"For all flesh is as grass, and all the glory of man as the flower of grass. The grass withereth, and the flower thereof falleth away:",
		"But the word of the Lord endureth for ever. And this is the word which by the gospel is preached unto you.",
		"Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evil speakings,",
		"As newborn babes, desire the sincere milk of the word, that ye may grow thereby:",
		"If so be ye have tasted that the Lord is gracious.",
		"To whom coming, as unto a living stone, disallowed indeed of men, but chosen of God, and precious,",
		"Ye also, as lively stones, are built up a spiritual house, an holy priesthood, to offer up spiritual sacrifices, acceptable to God by Jesus Christ.",
		"Wherefore also it is contained in the scripture, Behold, I lay in Sion a chief corner stone, elect, precious: and he that believeth on him shall not be confounded.",
		"Unto you therefore which believe he is precious: but unto them which be disobedient, the stone which the builders disallowed, the same is made the head of the corner,",
		"And a stone of stumbling, and a rock of offence, even to them which stumble at the word, being disobedient: whereunto also they were appointed.",
		"But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should show forth the praises of him who hath called you out of darkness into his marvellous light:",
		"Which in time past were not a people, but are now the people of God: which had not obtained mercy, but now have obtained mercy.",
		"Dearly beloved, I beseech you as strangers and pilgrims, abstain from fleshly lusts, which war against the soul;",
		"Having your conversation honest among the Gentiles: that, whereas they speak against you as evildoers, they may by your good works, which they shall behold, glorify God in the day of visitation.",
		"Submit yourselves to every ordinance of man for the Lord's sake: whether it be to the king, as supreme;",
		"Or unto governors, as unto them that are sent by him for the punishment of evildoers, and for the praise of them that do well.",
		"For so is the will of God, that with well doing ye may put to silence the ignorance of foolish men:",
		"As free, and not using your liberty for a cloak of maliciousness, but as the servants of God.",
		"Honour all men. Love the brotherhood. Fear God. Honour the king.",
		"Servants, be subject to your masters with all fear; not only to the good and gentle, but also to the froward.",
		"For this is thankworthy, if a man for conscience toward God endure grief, suffering wrongfully.",
		"For what glory is it, if, when ye be buffeted for your faults, ye shall take it patiently? but if, when ye do well, and suffer for it, ye take it patiently, this is acceptable with God.",
		"For even hereunto were ye called: because Christ also suffered for us, leaving us an example, that ye should follow his steps:",
		"Who did no sin, neither was guile found in his mouth:",
		"Who, when he was reviled, reviled not again; when he suffered, he threatened not; but committed himself to him that judgeth righteously:",
		"Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed.",
		"For ye were as sheep going astray; but are now returned unto the Shepherd and Bishop of your souls.",
		"Likewise, ye wives, be in subjection to your own husbands; that, if any obey not the word, they also may without the word be won by the conversation of the wives;",
		"While they behold your chaste conversation coupled with fear.",
		"Whose adorning let it not be that outward adorning of plaiting the hair, and of wearing of gold, or of putting on of apparel;",
		"But let it be the hidden man of the heart, in that which is not corruptible, even the ornament of a meek and quiet spirit, which is in the sight of God of great price.",
		"For after this manner in the old time the holy women also, who trusted in God, adorned themselves, being in subjection unto their own husbands:",
		"Even as Sara obeyed Abraham, calling him lord: whose daughters ye are, as long as ye do well, and are not afraid with any amazement.",
		"Likewise, ye husbands, dwell with them according to knowledge, giving honour unto the wife, as unto the weaker vessel, and as being heirs together of the grace of life; that your prayers be not hindered.",
		"Finally, be ye all of one mind, having compassion one of another, love as brethren, be pitiful, be courteous:",
		"Not rendering evil for evil, or railing for railing: but contrariwise blessing; knowing that ye are thereunto called, that ye should inherit a blessing.",
		"For he that will love life, and see good days, let him refrain his tongue from evil, and his lips that they speak no guile:",
		"Let him eschew evil, and do good; let him seek peace, and ensue it.",
		"For the eyes of the Lord are over the righteous, and his ears are open unto their prayers: but the face of the Lord is against them that do evil.",
		"And who is he that will harm you, if ye be followers of that which is good?",
		"But and if ye suffer for righteousness' sake, happy are ye: and be not afraid of their terror, neither be troubled;",
		"But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:",
		"Having a good conscience; that, whereas they speak evil of you, as of evildoers, they may be ashamed that falsely accuse your good conversation in Christ.",
		"For it is better, if the will of God be so, that ye suffer for well doing, than for evil doing.",
		"For Christ also hath once suffered for sins, the just for the unjust, that he might bring us to God, being put to death in the flesh, but quickened by the Spirit:",
		"By which also he went and preached unto the spirits in prison;",
		"Which sometime were disobedient, when once the longsuffering of God waited in the days of Noah, while the ark was a preparing, wherein few, that is, eight souls were saved by water.",
		"The like figure whereunto even baptism doth also now save us (not the putting away of the filth of the flesh, but the answer of a good conscience toward God,) by the resurrection of Jesus Christ:",
		"Who is gone into heaven, and is on the right hand of God; angels and authorities and powers being made subject unto him.",
		"Forasmuch then as Christ hath suffered for us in the flesh, arm yourselves likewise with the same mind: for he that hath suffered in the flesh hath ceased from sin;",
		"That he no longer should live the rest of his time in the flesh to the lusts of men, but to the will of God.",
		"For the time past of our life may suffice us to have wrought the will of the Gentiles, when we walked in lasciviousness, lusts, excess of wine, revellings, banquetings, and abominable idolatries:",
		"Wherein they think it strange that ye run not with them to the same excess of riot, speaking evil of you:",
		"Who shall give account to him that is ready to judge the quick and the dead.",
		"For for this cause was the gospel preached also to them that are dead, that they might be judged according to men in the flesh, but live according to God in the spirit.",
		"But the end of all things is at hand: be ye therefore sober, and watch unto prayer.",
		"And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.",
		"Use hospitality one to another without grudging.",
		"As every man hath received the gift, even so minister the same one to another, as good stewards of the manifold grace of God.",
		"If any man speak, let him speak as the oracles of God; if any man minister, let him do it as of the ability which God giveth: that God in all things may be glorified through Jesus Christ, to whom be praise and dominion for ever and ever. Amen.",
		"Beloved, think it not strange concerning the fiery trial which is to try you, as though some strange thing happened unto you:",
		"But rejoice, inasmuch as ye are partakers of Christ's sufferings; that, when his glory shall be revealed, ye may be glad also with exceeding joy.",
		"If ye be reproached for the name of Christ, happy are ye; for the spirit of glory and of God resteth upon you: on their part he is evil spoken of, but on your part he is glorified.",
		"But let none of you suffer as a murderer, or as a thief, or as an evildoer, or as a busybody in other men's matters.",
		"Yet if any man suffer as a Christian, let him not be ashamed; but let him glorify God on this behalf.",
		"For the time is come that judgment must begin at the house of God: and if it first begin at us, what shall the end be of them that obey not the gospel of God?",
		"And if the righteous scarcely be saved, where shall the ungodly and the sinner appear?",
		"Wherefore let them that suffer according to the will of God commit the keeping of their souls to him in well doing, as unto a faithful Creator.",
		"The elders which are among you I exhort, who am also an elder, and a witness of the sufferings of Christ, and also a partaker of the glory that shall be revealed:",
		"Feed the flock of God which is among you, taking the oversight thereof, not by constraint, but willingly; not for filthy lucre, but of a ready mind;",
		"Neither as being lords over God's heritage, but being ensamples to the flock.",
		"And when the chief Shepherd shall appear, ye shall receive a crown of glory that fadeth not away.",
		"Likewise, ye younger, submit yourselves unto the elder. Yea, all of you be subject one to another, and be clothed with humility: for God resisteth the proud, and giveth grace to the humble.",
		"Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time:",
		"Casting all your care upon him; for he careth for you.",
		"Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour:",
		"Whom resist stedfast in the faith, knowing that the same afflictions are accomplished in your brethren that are in the world.",
		"But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.",
		"To him be glory and dominion for ever and ever. Amen.",
		"By Silvanus, a faithful brother unto you, as I suppose, I have written briefly, exhorting, and testifying that this is the true grace of God wherein ye stand.",
		"The church that is at Babylon, elected together with you, saluteth you; and so doth Marcus my son.",
		"Greet ye one another with a kiss of charity. Peace be with you all that are in Christ Jesus. Amen.",
		"Simon Peter, a servant and an apostle of Jesus Christ, to them that have obtained like precious faith with us through the righteousness of God and our Saviour Jesus Christ:",
		"Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord,",
		"According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue:",
		"Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust.",
		"And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge;",
		"And to knowledge temperance; and to temperance patience; and to patience godliness;",
		"And to godliness brotherly kindness; and to brotherly kindness charity.",
		"For if these things be in you, and abound, they make you that ye shall neither be barren nor unfruitful in the knowledge of our Lord Jesus Christ.",
		"But he that lacketh these things is blind, and cannot see afar off, and hath forgotten that he was purged from his old sins.",
		"Wherefore the rather, brethren, give diligence to make your calling and election sure: for if ye do these things, ye shall never fall:",
		"For so an entrance shall be ministered unto you abundantly into the everlasting kingdom of our Lord and Saviour Jesus Christ.",
		"Wherefore I will not be negligent to put you always in remembrance of these things, though ye know them, and be established in the present truth.",
		"Yea, I think it meet, as long as I am in this tabernacle, to stir you up by putting you in remembrance;",
		"Knowing that shortly I must put off this my tabernacle, even as our Lord Jesus Christ hath showed me.",
		"Moreover I will endeavour that ye may be able after my decease to have these things always in remembrance.",
		"For we have not followed cunningly devised fables, when we made known unto you the power and coming of our Lord Jesus Christ, but were eyewitnesses of his majesty.",
		"For he received from God the Father honour and glory, when there came such a voice to him from the excellent glory, This is my beloved Son, in whom I am well pleased.",
		"And this voice which came from heaven we heard, when we were with him in the holy mount.",
		"We have also a more sure word of prophecy; whereunto ye do well that ye take heed, as unto a light that shineth in a dark place, until the day dawn, and the day star arise in your hearts:",
		"Knowing this first, that no prophecy of the scripture is of any private interpretation.",
		"For the prophecy came not in old time by the will of man: but holy men of God spake as they were moved by the Holy Ghost.",
		"But there were false prophets also among the people, even as there shall be false teachers among you, who privily shall bring in damnable heresies, even denying the Lord that bought them, and bring upon themselves swift destruction.",
		"And many shall follow their pernicious ways; by reason of whom the way of truth shall be evil spoken of.",
		"And through covetousness shall they with feigned words make merchandise of you: whose judgment now of a long time lingereth not, and their damnation slumbereth not.",
		"For if God spared not the angels that sinned, but cast them down to hell, and delivered them into chains of darkness, to be reserved unto judgment;",
		"And spared not the old world, but saved Noah the eighth person, a preacher of righteousness, bringing in the flood upon the world of the ungodly;",
		"And turning the cities of Sodom and Gomorrha into ashes condemned them with an overthrow, making them an ensample unto those that after should live ungodly;",
		"And delivered just Lot, vexed with the filthy conversation of the wicked:",
		"(For that righteous man dwelling among them, in seeing and hearing, vexed his righteous soul from day to day with their unlawful deeds;)",
		"The Lord knoweth how to deliver the godly out of temptations, and to reserve the unjust unto the day of judgment to be punished:",
		"But chiefly them that walk after the flesh in the lust of uncleanness, and despise government. Presumptuous are they, selfwilled, they are not afraid to speak evil of dignities.",
		"Whereas angels, which are greater in power and might, bring not railing accusation against them before the Lord.",
		"But these, as natural brute beasts, made to be taken and destroyed, speak evil of the things that they understand not; and shall utterly perish in their own corruption;",
		"And shall receive the reward of unrighteousness, as they that count it pleasure to riot in the day time. Spots they are and blemishes, sporting themselves with their own deceivings while they feast with you;",
		"Having eyes full of adultery, and that cannot cease from sin; beguiling unstable souls: an heart they have exercised with covetous practices; cursed children:",
		"Which have forsaken the right way, and are gone astray, following the way of Balaam the son of Bosor, who loved the wages of unrighteousness;",
		"But was rebuked for his iniquity: the dumb ass speaking with man's voice forbad the madness of the prophet.",
		"These are wells without water, clouds that are carried with a tempest; to whom the mist of darkness is reserved for ever.",
		"For when they speak great swelling words of vanity, they allure through the lusts of the flesh, through much wantonness, those that were clean escaped from them who live in error.",
		"While they promise them liberty, they themselves are the servants of corruption: for of whom a man is overcome, of the same is he brought in bondage.",
		"For if after they have escaped the pollutions of the world through the knowledge of the Lord and Saviour Jesus Christ, they are again entangled therein, and overcome, the latter end is worse with them than the beginning.",
		"For it had been better for them not to have known the way of righteousness, than, after they have known it, to turn from the holy commandment delivered unto them.",
		"But it is happened unto them according to the true proverb, The dog is turned to his own vomit again; and the sow that was washed to her wallowing in the mire.",
		"This second epistle, beloved, I now write unto you; in both which I stir up your pure minds by way of remembrance:",
		"That ye may be mindful of the words which were spoken before by the holy prophets, and of the commandment of us the apostles of the Lord and Saviour:",
		"Knowing this first, that there shall come in the last days scoffers, walking after their own lusts,",
		"And saying, Where is the promise of his coming? for since the fathers fell asleep, all things continue as they were from the beginning of the creation.",
		"For this they willingly are ignorant of, that by the word of God the heavens were of old, and the earth standing out of the water and in the water:",
		"Whereby the world that then was, being overflowed with water, perished:",
		"But the heavens and the earth, which are now, by the same word are kept in store, reserved unto fire against the day of judgment and perdition of ungodly men.",
		"But, beloved, be not ignorant of this one thing, that one day is with the Lord as a thousand years, and a thousand years as one day.",
		"The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.",
		"But the day of the Lord will come as a thief in the night; in the which the heavens shall pass away with a great noise, and the elements shall melt with fervent heat, the earth also and the works that are therein shall be burned up.",
		"Seeing then that all these things shall be dissolved, what manner of persons ought ye to be in all holy conversation and godliness,",
		"Looking for and hasting unto the coming of the day of God, wherein the heavens being on fire shall be dissolved, and the elements shall melt with fervent heat?",
		"Nevertheless we, according to his promise, look for new heavens and a new earth, wherein dwelleth righteousness.",
		"Wherefore, beloved, seeing that ye look for such things, be diligent that ye may be found of him in peace, without spot, and blameless.",
		"And account that the longsuffering of our Lord is salvation; even as our beloved brother Paul also according to the wisdom given unto him hath written unto you;",
		"As also in all his epistles, speaking in them of these things; in which are some things hard to be understood, which they that are unlearned and unstable wrest, as they do also the other scriptures, unto their own destruction.",
		"Ye therefore, beloved, seeing ye know these things before, beware lest ye also, being led away with the error of the wicked, fall from your own stedfastness.",
		"But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ. To him be glory both now and for ever. Amen."
	];

	//}
		/**
		 * Constructor
		 */
		 /*
		public function VerseColl()
		{
		}

		public function randomizeArray(array:Array):Array
		{
			var newArray:Array = new Array();
			while (array.length > 0)
			{
				var obj:Array = array.splice(Math.floor(Math.random() * array.length),1);
				newArray.push(obj[0]);
			}
			return newArray;
		}
		
		public function getJrRef(refidx:int):String
		{
			return "Success";
			//return jrRefs[refidx];
		}

		public function loadQuizData(selt:int, sels:int, sele:int, seln:int, selv:Boolean):Array
		{
			// make it where the number of verses is divisible by 5
			var numrepeats:uint = seln % 5;
			if (numrepeats > 0)
			{
				numrepeats = 5 - numrepeats;
			}
			var useArray:Array = jrVerses;
			var useIds:Array = jrIds;
			var useRefs:Array = jrRefs;
			if (selt > 1) {
				useArray = srVerses;
				useIds = srIds;
				useRefs = srRefs;
			}
			if (!selv) {
				useArray = getUniqueBeginnings(selt);
			}
			var verseItems:Array = new Array(seln+numrepeats);
			var mixedUp:Array = randomizeArray(useIds.slice(sels-1, sele));
			for (var i:uint=0; i<seln; i++)
			{
				verseItems[i] = new VerseItem(useArray[mixedUp[i]-1],useRefs[mixedUp[i]-1],mixedUp[i]);
			}
			for (var ii:uint=0; ii<numrepeats; ii++)
			{
				verseItems[seln + ii] = new VerseItem(useArray[mixedUp[ii]-1],useRefs[mixedUp[ii]-1],mixedUp[ii]);
			}
			return verseItems;
		}
		
		public function getUniqueBeginnings(selt:int):Array //returns a string array of unique beginnings
		{
        var verses:Array = jrVerses;
        if (selt == 0) {
            verses = jrVerses.slice(0, 281);
        } else if (selt == 2) {
			verses = srVerses.slice(0,428);
		} else if (selt == 3) {
			verses = srVerses;
		}

 		var pos:int;
        var tempStr:String = "";
 		var foundMatch:Boolean;
        var wordidx:int;
        var verseIdx:int;
        var beginnings:Array = new Array(verses.length);
        for (var i:uint=0; i<verses.length; i++) {
            foundMatch = true;
            wordidx = 1;
            while (foundMatch) {
                foundMatch = false;
                if (wordidx <= verses[i].length) {
                tempStr = verses[i].slice(0,wordidx);
                verseIdx = 0;
                while ((verseIdx < verses.length) && (!foundMatch)) {
                    if ((verses[verseIdx].indexOf(tempStr, 0) == 0) && (verseIdx != i)) {
                        foundMatch = true;
                    }
                    verseIdx++;
                }
                wordidx++;
                }
            }
            wordidx--;
            pos = verses[i].indexOf(" ", wordidx);
            if (pos == -1) {
                beginnings[i] = verses[i];
            } else {
                beginnings[i] = verses[i].slice(0,pos);
            }
        }
        return beginnings;
    }

		public function getSummary(selt:int, sels:int, sele:int, seln:int, nwrong:int):String
		{
			var useRefs:Array = jrRefs;
			if (selt > 1) {
				useRefs = srRefs;
			}
			//trace("(" + useRefs[sels-1] + "-" + useRefs[sele-1] + ", " + seln + ", " + nwrong + " wrong)");
			return "(" + useRefs[sels-1] + "-" + useRefs[sele-1] + ", " + seln + ", " + nwrong + " wrong)";
		}

	}*/
//}
